#!/usr/bin/env bash
# Tier 2 B2: stage raw downloads for GTEx v8 (Liver cis-eQTL) + UKB-derived
# LDL-cholesterol GWAS sumstats, harmonized to a common SNP set at the
# SORT1 cis locus (chr1p13). Implements the paper Tier 2 dispatch brief
# (docs/superpowers/plans/2026-05-15-paper-tier123-agent-briefs.md §5 B2).
#
# Strategy:
#   - GTEx v8 single-tissue cis-eQTL significant pairs (Liver) -- 1.5 GB tar
#     from the public adult-gtex GCS bucket; we only extract Liver.
#   - UKB-derived LDL GWAS -- we use the GLGC 2021 LDL harmonised release
#     (Graham et al. Nature 2021, GCST90239658) from the EBI GWAS Catalog,
#     which incorporates UKB Biomarker biochemistry data (n_UKB ~ 350K of
#     n_total ~ 1.65M) and is already aligned to GRCh38, matching the
#     GTEx v8 reference. See README.md § Data sources for the rationale.
#
# Pre-flight (per memory/feedback_preflight.md and the brief): asserts
# at least 5 GB free disk on /home and 8 GB available RAM before touching
# the network. Aborts non-zero on insufficient resources.
#
# Idempotent: re-runs leave already-cached downloads untouched.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CACHE_DIR="${HERE}/.cache"
FIXTURES_DIR="${HERE}/fixtures"
mkdir -p "${CACHE_DIR}" "${FIXTURES_DIR}"

# shellcheck source=../../external/_lib/preflight.sh
source "${HERE}/../../external/_lib/preflight.sh"

# Brief: at least 5 GB disk + 8 GB RAM.
preflight_check "gtex_ukb-fetch" 5 8

# --- Source 1: GTEx v8 single-tissue cis-eQTL significant pairs tar -----
GTEX_URL="https://storage.googleapis.com/adult-gtex/bulk-qtl/v8/single-tissue-cis-qtl/GTEx_Analysis_v8_eQTL.tar"
GTEX_TAR="${CACHE_DIR}/GTEx_Analysis_v8_eQTL.tar"
# SHA256 captured 2026-05-15 from a verified download against the public bucket.
GTEX_TAR_SHA256="c61ac336daf86a92f1596ee59de7dd5e60d451a507a6d7a15d8b030a0266ac5d"

if [[ ! -f "${GTEX_TAR}" ]]; then
    echo "[gtex_ukb fetch] downloading GTEx v8 cis-eQTL tar (≈1.5 GB)..."
    curl -L --fail --silent --show-error --max-time 3600 \
         --output "${GTEX_TAR}" "${GTEX_URL}"
else
    echo "[gtex_ukb fetch] cached: ${GTEX_TAR}"
fi

# Verify against the pinned SHA256 (hard abort on mismatch via preflight.sh).
verify_checksum "${GTEX_TAR}" "${GTEX_TAR_SHA256}"
GTEX_TAR_OBSERVED="${GTEX_TAR_SHA256}"
echo "[gtex_ukb fetch] GTEx tar SHA256 OK: ${GTEX_TAR_OBSERVED}"

# --- Source 2: GLGC 2021 LDL harmonised GWAS (UKB-inclusive) -----------
# Graham et al., Nature 2021, GLGC trans-ancestry meta-analysis of LDL-C.
# GWAS Catalog accession: GCST90239658.
GLGC_URL="https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90239001-GCST90240000/GCST90239658/harmonised/GCST90239658.h.tsv.gz"
GLGC_GZ="${CACHE_DIR}/GCST90239658.h.tsv.gz"
GLGC_GZ_SHA256="c0f0841fa65e2863bfc66325154265e19b6742c423fe5ae8d80499ed9abf1037"

if [[ ! -f "${GLGC_GZ}" ]]; then
    echo "[gtex_ukb fetch] downloading GLGC 2021 LDL harmonised GWAS (≈1.4 GB)..."
    curl -L --fail --silent --show-error --max-time 3600 \
         --output "${GLGC_GZ}" "${GLGC_URL}"
else
    echo "[gtex_ukb fetch] cached: ${GLGC_GZ}"
fi

verify_checksum "${GLGC_GZ}" "${GLGC_GZ_SHA256}"
GLGC_GZ_OBSERVED="${GLGC_GZ_SHA256}"
echo "[gtex_ukb fetch] GLGC LDL SHA256 OK: ${GLGC_GZ_OBSERVED}"

# --- Extract Liver-only files from the GTEx tar ------------------------
GTEX_LIVER_DIR="${CACHE_DIR}/GTEx_Analysis_v8_eQTL"
if [[ ! -f "${GTEX_LIVER_DIR}/Liver.v8.signif_variant_gene_pairs.txt.gz" ]]; then
    echo "[gtex_ukb fetch] extracting Liver from tar..."
    tar -xf "${GTEX_TAR}" -C "${CACHE_DIR}" \
        GTEx_Analysis_v8_eQTL/Liver.v8.signif_variant_gene_pairs.txt.gz \
        GTEx_Analysis_v8_eQTL/Liver.v8.egenes.txt.gz
fi

# --- Persist staged paths + observed checksums for prepare.py ----------
cat > "${HERE}/.env_marker" <<EOF
# Auto-generated by fetch.sh; consumed by prepare.py.
GTEX_TAR=${GTEX_TAR}
GTEX_TAR_SHA256=${GTEX_TAR_OBSERVED}
GTEX_LIVER_SIGNIF=${GTEX_LIVER_DIR}/Liver.v8.signif_variant_gene_pairs.txt.gz
GTEX_LIVER_EGENES=${GTEX_LIVER_DIR}/Liver.v8.egenes.txt.gz
GLGC_GZ=${GLGC_GZ}
GLGC_GZ_SHA256=${GLGC_GZ_OBSERVED}
EOF

echo "[gtex_ukb fetch] DONE."
echo "  GTEx tar:    ${GTEX_TAR}"
echo "  GTEx Liver:  ${GTEX_LIVER_DIR}/Liver.v8.signif_variant_gene_pairs.txt.gz"
echo "  GLGC LDL:    ${GLGC_GZ}"
echo ""
echo "Next: python3 ${HERE}/prepare.py"
echo "      (writes fixtures/{gtex_liver_sort1.tsv.gz, ukb_ldl_sort1.tsv.gz,"
echo "                        aligned.parquet, manifest.sha256})"
